export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const SEARCH_POKEMON = 'SEARCH_POKEMON';
export const RESET_STATE = 'RESET_STATE';
export const ORDER_POKEMONS = 'ORDER_POKEMONS';
export const FILTER_POKEMONS = 'FILTER_POKEMONS';
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const CREATE_POKEMON = 'CREATE_POKEMON';
export const GET_ALL_TYPES = 'GET_ALL_TYPES';